chore: add check-pr-title GH action
dasch-swiss/dsp-ingest pull request #92
Opened 2023-09-15 13:52 UTC by mpro7

2023-09-18 07:19 UTC, seakayone requested changes

2023-09-18 07:19 UTC, seakayone commented on .github/workflows/check-pr-title
> +          regex: '^(feat|fix|docs|chore)(\(.+\))?!?: .+$'
What about `refactor`?

2023-09-18 11:54 UTC, seakayone approved these changes

2023-09-19 06:58 UTC, BalduinLandolt approved these changes

2023-09-19 07:24 UTC, merged